name: dart_swagger_generator
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  basic_utils: ^5.4.0
  collection: ^1.17.0
  swagger_parser:
    git: 
      url: https://github.com/qscr/swagger_parser.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
